{{- if .Values.homer.ingress.enabled -}}
{{- $httpPort := .Values.homer.service.ports.http -}}
{{- $fullName := include "homer.fullname" . -}}
{{- $svcPort := .Values.homer.service.ports.http -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "common.labels" . | nindent 4 }}
  {{- with .Values.homer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.homer.ingress.className }}
  ingressClassName: {{ .Values.homer.ingress.className | quote }}
  {{- end }}
  {{- if .Values.homer.ingress.tls }}
  tls:
    {{- range .Values.homer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.homer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default $.Values.homer.ingress.pathtype | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $httpPort }}
          {{- end }}
    {{- end }}
{{- end }}
